changed codes.yaml

diff --git a/.github/workflows/codes.yaml b/.github/workflows/codes.yaml
--- a/.github/workflows/codes.yaml
+++ b/.github/workflows/codes.yaml
@@ -44,27 +44,27 @@ jobs:
         uses: hashicorp/setup-terraform@v3
         #with:
         #  terraform_version: "1.10.5"
-     
-      - name: Terraform init
-        id: init
-        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE" -backend-config="key=terraform.tfstate" -backend-config="region=$AWS_REGION"
-
+    
       - name: Terraform format
         id: fmt
         run: terraform init -check
 
-      - name: Terraform validate
-        id: validate
-        run: terraform validate
+      - name: Terraform init
+        id: init
+        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE" -backend-config="key=terraform.tfstate" -backend-config="region=$AWS_REGION"
+      
+      # - name: Terraform validate
+      #   id: validate
+      #   run: terraform validate
 
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color -input-false -out planfile
-        continue-on-error: true
+      # - name: Terraform plan
+      #   id: plan
+      #   run: terraform plan -no-color -input-false -out planfile
+      #   continue-on-error: true
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform plan status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       # - name: Terraform apply
       #   id: t-apply
